### ISSUE TITLE
Did you run benchmark against SPIFFS ?

### ISSUE THREAD

**Issue by X-Ryl669** [joltwallet/esp_littlefs#1]
You're saying that SPIFFS is slower than littlefs. How do you know that ? Is it actually proved, or just a rumor from a forum test ?

**Comment by BrianPugh** [comment]
I can post some simple benchmarking results later this week. If memory serves me correctly, this port of LittleFS was ~3x faster than SPIFFS and the margin grows significantly as more files are added and the partition fills.

**Comment by BrianPugh** [comment]
Codebase and README has been updated with some naive benchmarking code.

SPIFFS drastically slows down as files are created, which was the primary reason for us to port LittleFS.

**Comment by BrianPugh** [comment]
closing this issue for now
