### ISSUE TITLE
managed_components\joltwallet__littlefs\mklittlefs && make dist error

### ISSUE THREAD

**Issue by staunchheart** [joltwallet/esp_littlefs#103]
windows 10 
mingw gcc 8.10

MAKE Version 5.2  Copyright (c) 1987, 1998 Inprise Corp.
Error makefile 3: Command syntax error
Error makefile 4: Command syntax error
Error makefile 6: Command syntax error
Error makefile 8: Command syntax error
......

**Comment by BrianPugh** [comment]
Duplicate of #102
