### ISSUE TITLE
littlefs-1.5.0 build failure with esp-idf v5.1-dev-1736-g056d72ece5

### ISSUE THREAD

**Issue by AxelLin** [joltwallet/esp_littlefs#104]
Hit below build error after update esp-idf master:
managed_components/joltwallet__littlefs/src/littlefs_api.c:10:10: fatal error: esp_partition.h: No such file or directory
   10 | #include "esp_partition.h"
      |          ^~~~~~~~~~~~~~~~~

Looks like it needs to add REQUIRES "esp_partition" dependency.

**Comment by BrianPugh** [comment]
Hi Axel! Can you open up a PR with the fix? Thanks!

**Comment by BrianPugh** [comment]
actually i'll work on it, i need to update the CI anyways.

**Comment by BrianPugh** [comment]
released v1.5.1 that should fix this!
