### ISSUE TITLE
Suggestion: adding Kconfig options for LittleFS debug level.

### ISSUE THREAD

**Issue by everslick** [joltwallet/esp_littlefs#109]
As documented here: https://github.com/espressif/esp32-arduino-lib-builder/issues/103 and here: https://github.com/espressif/arduino-esp32/issues/7700 it would be nice, if we could disable serial output in a clean and consistent way.

**Comment by igrr** [comment]
And as a follow-up, an alternative suggestion is to define littleFS logging macros to ESP-IDF ones. Then the log level can be directly controlled via ESP-IDF configuration options, esp_log_level_set, and log redirection will also work.

**Comment by BrianPugh** [comment]
thanks guys! I'm currently pretty busy, but totally open to pull requests. Otherwise, I'll try and get to this sometime in the next few weeks.

**Comment by BrianPugh** [comment]
@frozen-eye Not sure what your schedule is like, but this might be relevant to your last PR. I haven't had the time to work on this, but would gladly accept PRs.

**Comment by BrianPugh** [comment]
Will be included in upcoming 1.5.4
