### ISSUE TITLE
basePath="/"

### ISSUE THREAD

**Issue by lorol** [joltwallet/esp_littlefs#11]
Hi Brian,

Can you please verify, I believe, for SPIFFS is OK to load it to basePath="/" but for LittleFS I had to use basePath="" instead.
The "/" compiles and runs, but webpages of my app go to "not-found". It could be related to the application itself but i think, the root "/" is somehow differently interpreted in lfs, and care should be taken anyway.
I would force the choice basePath="/" to be   basePath="" to solve my sketches, but is this a good way?

**Comment by BrianPugh** [comment]
I can try and investigate this either this evening or this weekend and I'll add a unit-test for it. It sounds like undesirable behavior

**Comment by lorol** [comment]
Thanks ...
See this, maybe related:
https://github.com/ARMmbed/littlefs/issues/138

**Comment by BrianPugh** [comment]
Investigating this on branch `root_mount`. I've so far added a unit-test that confirms your findings.

The primary issue seems to be [this line in the esp-idf vfs component](https://github.com/espressif/esp-idf/blob/625bd5eb1806809ff3cc010ee20d1f750aa778a1/components/vfs/vfs.c#L78). I'll do a quick investigation on how/why spiffs handles it fine. It probably involves explicitly checking for `"/"` and then passing along a 0-length string.

**Comment by BrianPugh** [comment]
[according to the VFS documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/vfs.html#_CPPv416esp_vfs_registerPKcPK9esp_vfs_tPv), `"/"` is an invalid base_path.

Still figuring out what to do/what is implied that might not be properly documents by the VFS code-base.

**Comment by lorol** [comment]
Ok, i just forced this to become "" :)

**Comment by lorol** [comment]
For sketches I am using actually the mounting point doesn't matter at all.

**Comment by BrianPugh** [comment]
I'm gonna mess around with this a little more and report what I find here.

**Comment by lorol** [comment]
Ok, you may check with this developer too:
https://github.com/earlephilhower/arduino-esp8266littlefs-plugin/issues/9

**Comment by BrianPugh** [comment]
@lorol are you sure you're able to use `"/"` as a basepath? I'm unable to do this with SPIFFS (it fails the same logic).

In a similar note, I opened[ this issue](https://github.com/espressif/esp-idf/issues/5514) on the esp-idf repo questioning the path validation logic.

**Comment by lorol** [comment]
I will check maybe I messed up the tings with ESP8266

**Comment by BrianPugh** [comment]
[Igrr confirmed](https://github.com/espressif/esp-idf/issues/5514#issuecomment-650828458) that `"/"` is not a valid mounting point, so I'll mark this as closed for now. Thanks!

**Comment by lorol** [comment]
Yes, you are right it was my mistake.
