### ISSUE TITLE
littlefs/lfs.h missing

### ISSUE THREAD

**Issue by blb92123** [joltwallet/esp_littlefs#13]
Hi there,
I've added littlefs submodule to my esp_idf environment, but when I compile I get 
"/components/esp_littlefs/src/littlefs_api.c:12:10: fatal error: littlefs/lfs.h: No such file or directory"
There is a littlefs directory in the repository but it is empty.  

Thanks for putting in the work on this port,
Barry

**Comment by BrianPugh** [comment]
Run:

git submodule update --init --recursive

**Comment by blb92123** [comment]
Awesome that was it!  Thanks very much!
