### ISSUE TITLE
Windows support of mklittlefs

### ISSUE THREAD

**Issue by eeyrw** [joltwallet/esp_littlefs#133]
When trying to use mklittlefs under Windows you may get:
```
[1/11] Generating ../../../managed_components/joltwallet__littlefs/mklittlefs/mklittlefs
FAILED: ../managed_components/joltwallet__littlefs/mklittlefs/mklittlefs C:/Users/yuan/Desktop/advanced-auto-watering/managed_components/joltwallet__littlefs/mklittlefs/mklittlefs
cmd.exe /C "cd /D C:\Users\yuan\Desktop\advanced-auto-watering\managed_components\joltwallet__littlefs\mklittlefs && make clean 
&& make dist LFS_NAME_MAX=64"
'make' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```
Is it possible to provide an executable when using Windows rather than building mklittlefs on the fly?

**Comment by RodrigoStefanini** [comment]
My issues report is about that... [link](https://github.com/joltwallet/esp_littlefs/issues/132)

**Comment by eeyrw** [comment]
After looking into your issue,it seems that we are talking about same things. If Windows supporting is limited or requiring other preparation, it could be better making those limitations mentioned in README.

**Comment by RodrigoStefanini** [comment]
Have you tried compiling on another operating system and succeeded? Which was used?

**Comment by BrianPugh** [comment]
closing this issue in favor of #132, which has more detail.
