### ISSUE TITLE
Missing execinfo.h

### ISSUE THREAD

**Issue by ProjectRobal** [joltwallet/esp_littlefs#136]
I am trying to compile esp_littlefs under PlatformIO. I have put it in components folder in root directory of my project. I have run git command with recursive option. But it doesn't want to compile at first it complained about missing some includes from littlefs subfolders after some tweaking with esp_littlefs CMakeLists.txt I have got that error message:

*** [.pio/build/esp32-s3/libf3d/esp_littlefs/littlefs/runners/bench_runner.o] Error 1
.pio/libdeps/esp32-s3/esp_littlefs/src/littlefs/runners/test_runner.c:23:10: fatal error: execinfo.h: No such file or directory

And here is modified CMakeLists.txt:

[CMakeLists.txt](https://github.com/joltwallet/esp_littlefs/files/12221643/CMakeLists.txt)

And here are error messages before tweaking with cmake:

.pio/libdeps/esp32-s3/esp_littlefs/src/littlefs/bd/lfs_filebd.c:8:10: fatal error: bd/lfs_filebd.h: No such file or directory
    8 | #include "bd/lfs_filebd.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
.pio/libdeps/esp32-s3/esp_littlefs/src/littlefs/bd/lfs_emubd.c:14:10: fatal error: bd/lfs_emubd.h: No such file or directory
   14 | #include "bd/lfs_emubd.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/esp32-s3/libf3d/esp_littlefs/littlefs/bd/lfs_filebd.o] Error 1
*** [.pio/build/esp32-s3/libf3d/esp_littlefs/littlefs/bd/lfs_emubd.o] Error 1
.pio/libdeps/esp32-s3/esp_littlefs/src/littlefs/bd/lfs_rambd.c:8:10: fatal error: bd/lfs_rambd.h: No such file or directory
    8 | #include "bd/lfs_rambd.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/esp32-s3/libf3d/esp_littlefs/littlefs/bd/lfs_rambd.o] Error 1

**Comment by BrianPugh** [comment]
I haven't used PlatformIO in any serious capacity, so I'm not experienced in what the issue would be. I'd find it odd that you would need to tweak the CMakeLists.txt as you did (removing `src/littlefs` from includes).

Not sure why it's unable to find `execinfo.h`, it should be provided by esp-idf.

**Comment by ProjectRobal** [comment]
Sorry for problems, my platformio configuration was messed up. Apparently I had two instances of esp_littlefs in my project. After removing one instance everything is building as it should be.
