### ISSUE TITLE
clean built files FAILED

### ISSUE THREAD

**Issue by wankey** [joltwallet/esp_littlefs#149]
Executing action: clean
Running ninja in directory /Users/wankey/Documents/Work/code/build
Executing "ninja clean"...
[2/2] Cleaning all built files...FAILED: clean 
/usr/local/bin/ninja  -t clean 
Cleaning... ninja: error: remove(littlefs_py_venv): Directory not empty
ninja: error: remove(/Users/wankey/Documents/Work/code/build/littlefs_py_venv): Directory not empty
1138 files.
ninja: build stopped: subcommand failed.

**Comment by BrianPugh** [comment]
@ianlevesque not to drag you in, but do you have a solution for this?

**Comment by ianlevesque** [comment]
Ah probably need to set [ADDITIONAL_CLEAN_FILES](https://cmake.org/cmake/help/latest/prop_dir/ADDITIONAL_CLEAN_FILES.html) somewhere. I'm not likely to get to it right away.

**Comment by BrianPugh** [comment]
thanks! I got it!

**Comment by BrianPugh** [comment]
should be fixed in v0.9.2
