### ISSUE TITLE
Failed to build, error with `block_count`

### ISSUE THREAD

**Issue by guo-max** [joltwallet/esp_littlefs#157]
Got this error when try to build with version 1.10.2 from master branch. 
![image](https://github.com/joltwallet/esp_littlefs/assets/27696259/bdaf8d25-b7fb-44bc-949d-8fd30ad59e13)

``` 
   void get_total_and_used_bytes(esp_littlefs_t *efs, size_t *total_bytes, size_t *used_bytes) {
    sem_take(efs);
    size_t total_bytes_local = efs->cfg.block_size * efs->fs->block_count;
  ...
```

I checked the early version, before Version 1.10.0, this function is like this
```
void get_total_and_used_bytes(esp_littlefs_t *efs, size_t *total_bytes, size_t *used_bytes) {
    sem_take(efs);
    size_t total_bytes_local = efs->cfg.block_size * efs->cfg.block_count;
   ...
 }
```
Is this a bug?

**Comment by BrianPugh** [comment]
are you building this from cloning this repo? Make sure to run a `git submodule update`

**Comment by guo-max** [comment]
> are you building this from cloning this repo? Make sure to run a `git submodule update`

Thanks for your quick reply. I downloaded the `zip` file. I will try to clone and update the submodule.

**Comment by guo-max** [comment]
issue fixed after update submodule.
Thanks again.
