### ISSUE TITLE
littlefs_create_partition_image not found

### ISSUE THREAD

**Issue by ctag-fh-kiel** [joltwallet/esp_littlefs#160]
Hi,

I use esp_littlefs as managed component in my project through the idf_component.yml file.
However, when I want to use littlefs_create_partition_image() in my base CMakeLists.txt file, littlefs_create_partition_image is not found. 

What I am missing, is this an issue?

Thanks for any help

**Comment by ctag-fh-kiel** [comment]
I have added this before the littlefs_create... statement:
include(managed_components/joltwallet__littlefs/project_include.cmake)

ok?

**Comment by BrianPugh** [comment]
that's expected behavior for esp-idf's build system.

**Comment by ctag-fh-kiel** [comment]
Great, it may help to add this as a hint for using esp_littlefs with managed components.
