### ISSUE TITLE
[question] File creation while iterating

### ISSUE THREAD

**Issue by danielbuechele** [joltwallet/esp_littlefs#171]
I'm iterating a directory using `readdir`. What is the behavior when another task creates a new file while I'm iterating in the first task. Will the new file be "invisible", will I iterate the newly created file or is the behavior unspecified?

Or is this a question I should rather directly ask on the littleFS repo?

**Comment by BrianPugh** [comment]
I *think* this is an upstream question. Basically the question is: "if a file is created after lfs_dir_open is called, is it included in the traversal?"

**Comment by danielbuechele** [comment]
Yeah, I thought so. I did some tests myself and it looks like files are generally iterated in alphabetical order. If the newly created file has a filename that is later in the alphabet it would be included in the iteration, if my loop was already past the point it wouldn't be included.

Thanks for your quick reply!
