### ISSUE TITLE
Was version 1.14.2 correctly uploated to ESP component registy?

### ISSUE THREAD

**Issue by adokitkat** [joltwallet/esp_littlefs#182]
Hi.

I noticed I cannot find the new 1.14.2 version in [ESP component registry](https://components.espressif.com/components/joltwallet/littlefs), only v1.14.1.

If you look at [this job](https://github.com/joltwallet/esp_littlefs/actions/runs/8175500233/job/22352745524) which started when new version was tagged and click on "Upload component to component service", there is the last line "Saving archive to "/github/workspace/dist/LittleFS_1.14.1.tgz" - and it seems it wasn't uploaded because of that since v1.14.1 it's already there? [An example](https://github.com/joltwallet/esp_littlefs/actions/runs/7807372008/job/21295644143) of the previous version which did upload correctly. 

I am not sure why it happen though. Also the README.me wasn't updated as well but that's just a cosmetic issue 😄

**Comment by BrianPugh** [comment]
ugh you're totally right, fixing now.

**Comment by BrianPugh** [comment]
thanks for the ping! This repo has a slightly different release process than most of my other repos and it slipped my mind. This should all be good to go now!

**Comment by adokitkat** [comment]
No problem, thank you for such quick replies.
