### ISSUE TITLE
littlefs_create_partition_image does not create the binary

### ISSUE THREAD

**Issue by AndresSingularThings** [joltwallet/esp_littlefs#193]
I’m using ESP-IDF v5.2.2-272-gabf8ffac59 and joltwallet/littlefs (1.14.7).

The issue I’m facing is that the partition binary is not being created. When I attempt to flash, I encounter the following error: `write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: 'prv.bin'.`

In the CMakeLists.txt file, I have the following: `littlefs_create_partition_image(prv lfs_private_content FLASH_IN_PROJECT).`

I’m not sure what happened. In version 1.14.4, it worked fine, but now when I downgrade, I encounter the same problem.

**Comment by dovydas1928** [comment]
we are having the same issue, waiting v1.14.8

**Comment by BrianPugh** [comment]
please give v1.14.8 a try now.

**Comment by dovydas1928** [comment]
perfect. now works. thanks!

**Comment by BrianPugh** [comment]
great! sorry for the original breaking build! glad it works now!
