### ISSUE TITLE
ESP build process fails due to 'unrecognised argument'

### ISSUE THREAD

**Issue by Teesmo** [joltwallet/esp_littlefs#195]
I am using LittleFS in my application to store sensor readings. I have tested it before, and the code built and worked well. Now, I have effected some changes in my application (added functionality not related to littlefs), and I get this error when I build my project 
`littlefs-python: error: unrecognized arguments: --image=`
I don't know why I am getting this error, since the code has built before. The only other thing I did is I pushed some previous code to github, but I don't know how this would affect the build of my application. Please help!!!
@adokitkat

**Comment by BrianPugh** [comment]
update to the latest version (v1.14.8) and it should be resolved.
