### ISSUE TITLE
Filesystem Image Creation documentation

### ISSUE THREAD

**Issue by avanti1** [joltwallet/esp_littlefs#204]
I spent a day trying to get the "littlefs_create_partition_image" feature working. I finally found out that if you actually want it to move your files to flash, you need to add the string "FLASH_IN_PROJECT" as a third parameter.  I think it would help people if this were noted. 

It should look something like this:
littlefs_create_partition_image(littlefs /esp/littlefsfiles FLASH_IN_PROJECT)

**Comment by BrianPugh** [comment]
So sorry about that! I just updated the README in [28639dd](https://github.com/joltwallet/esp_littlefs/commit/28639dd469af0b33df55d481da8383347e88067e) to reflect that most people should probably be adding `FLASH_IN_PROJECT` to their `littlefs_create_partition_image` call. Thanks for reporting this!
