### ISSUE TITLE
need a littlefs_stream 

### ISSUE THREAD

**Issue by shishirong** [joltwallet/esp_littlefs#210]
similar spiffs_stream.h

**Comment by BrianPugh** [comment]
are you referencing [this](https://github.com/espressif/esp-adf/blob/master/components/audio_stream/include/spiffs_stream.h)? I'm open to a PR, but I don't intend to implement it myself.

**Comment by shishirong** [comment]
Yes, I tried to replace all SPIFFS with LittleFS, and it works. If it is added to esp_littlefs, it will be more convenient.
