### ISSUE TITLE
Missing submodule components/esp_littlefs/littlefs

### ISSUE THREAD

**Issue by siara-cc** [joltwallet/esp_littlefs#27]
Hi,

Thank you for making this repo.

When I was trying this out with esp-idf 4.1.1 on MacOS, I was getting this error and could not proceed further for `make tests`:
```
WARNING: Missing submodule components/esp_littlefs/littlefs...
Attempting 'git submodule update --init components/esp_littlefs/littlefs' in esp-idf root directory...
error: pathspec 'components/esp_littlefs/littlefs' did not match any file(s) known to git
make: *** [/Users/arun/esp/esp-idf/components/esp_littlefs/littlefs/.git] Error 1
```
I also hit the same error when trying out `https://github.com/wreyford/demo_esp_littlefs`.
I could proceed further only when I ran `cp -R src/littlefs .` in `components/esp_littlefs` folder.

Not sure if only I am getting this error. Just FYI.

**Comment by BrianPugh** [comment]
hmmm, depending on your project structure, try `git submodule update --init --recursive`
