### ISSUE TITLE
esp_littlefs_api: failed to read addr 00123000, size 00000200, err 257

### ISSUE THREAD

**Issue by ghtech** [joltwallet/esp_littlefs#28]
Hi we are using littlefs  to store JSON files as database 

we have about 60+ files . we have noticed some time we get err 257 to read couple of files but rest of files read and write keep working fine
we can write to same file but read does not work 
after reboot  Esp32 problem solved and every thing start working fine 
````
E (4556059) esp_littlefs_api: failed to read addr 000c4400, size 00000200, err 257
E (4556067) esp_littlefs_api: failed to read addr 000c4000, size 00000080, err 257

E (201284) esp_littlefs_api: failed to read addr 00123000, size 00000200, err 257
E (201288) esp_littlefs_api: failed to read addr 00123000, size 00000080, err 257
````
Please let me know if you have any idea main cause of this problem 
Thanks 
Farhan

**Comment by BrianPugh** [comment]
so this seems like a more generic esp-idf issue. This error is being logged here:

https://github.com/joltwallet/esp_littlefs/blob/d268e18d774431fb6f0e444feef4e97a2dfaaa29/src/littlefs_api.c#L24

from `esp_partition_read` failing:

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/spi_flash.html#_CPPv418esp_partition_readPK15esp_partition_t6size_tPv6size_t

Not sure if err 257 is `ESP_ERR_INVALID_ARG` or `ESP_ERR_INVALID_SIZE`, but hopefully this might help a little.
