### ISSUE TITLE
File copy between partitions

### ISSUE THREAD

**Issue by ndjur** [joltwallet/esp_littlefs#58]
Hi,
Would you please tell me how to copy files between littleFS formatted partitions.
Also, in order to empty a partition, is it faster/safer to erase the whole partition (using esp_partition_erase_range() for instance), to format a partition or to delete all files from a partition.
Thank you very much.

**Comment by BrianPugh** [comment]
I would just read the old file chunks into a temporary buffer and write it to the new partition.

As for emptying a partition, call `esp_littlefs_format(const char* partition_label)`

**Comment by ndjur** [comment]
Thanks a lot. I'll format the partition in order to clear all da from it.
