### ISSUE TITLE
LittleFS & Flash Encryption on ESP32

### ISSUE THREAD

**Issue by dmitrij9992905** [joltwallet/esp_littlefs#63]
Hello!

I'm targeting to use the filesystem to store file-represented data on encrypted partition.
As I see from README, there are unit tests on encrypted partition, but there is SPIFFS in table that doesn't work with Flash Encryption properly.

Does the LittleFS work with encrypted partition in real case?

**Comment by BrianPugh** [comment]
it should work with encryption, the `spiffs` in the table is just because there isn't an official `littlefs` in the partition creation tool.

**Comment by BrianPugh** [comment]
I have confirmed it works with `CONFIG_SECURE_FLASH_ENC_ENABLED=y`, but i haven't experimented it with release mode or explicitly looked at the flash contents.
